STREAMING_CHUNK:Setting up base python image...
STREAMING_CHUNK:Installing ffmpeg...
STREAMING_CHUNK:Configuring working directory...
STREAMING_CHUNK:Installing python dependencies...
STREAMING_CHUNK:Copying application source code...
STREAMING_CHUNK:Exposing server port...
STREAMING_CHUNK:Starting uvicorn server...
